### ISSUE TITLE
Panic if no custom prime set

### ISSUE THREAD

**Issue by joshlf** [c2h5oh/hide#1]
Having the package work properly with defaults is dangerous because it fails open - failure to configure doesn't break usability, but silently removes almost all security. A better option would be to keep track of whether custom primes had been set, and if not, panic. If usability for development is a concern, have a `SetDefaultPrimes` function or similar so that security must be weakened intentionally rather than by accident.

**Comment by c2h5oh** [comment]
Good point and I definitely will make that change at the same time I update docs - based on reddit response I have to make it absolutely clear this is only obfuscation not full crypto.

Hopefully I'll find time for that this weekend, but pull requests are always welcome.

**Comment by joshlf** [comment]
Ah yes. Always important to document defensively when you're implementing security stuff, or you never know what magic people will believe your tech is capable of ;)

**Comment by c2h5oh** [comment]
It has taken way longer than I would have liked, but default primes are now gone :-)
