### ISSUE TITLE
Custom primes

### ISSUE THREAD

**Issue by teodor-pripoae** [c2h5oh/hide#3]
I'm trying to port it to Crystal, [here](https://github.com/kuende/bisani).

Your package doesn't work with custom primes using `hide.Default.SetInt32`.

``` go
package main

import (
    "fmt"
    "math/big"

    "github.com/c2h5oh/hide"
)

func test(v int32) {
    x := hide.Int32Deobfuscate(hide.Int32Obfuscate(v, nil), nil)
    fmt.Printf("res for %d is %d\n", v, x)
}

func main() {
    test(100)

    hide.Default.SetInt32(big.NewInt(1154853319))

    test(100)
}
```

This returns:

```
$ go run cmd/example.go
res for 100 is 100
res for 100 is 1671838784
```

If I change [here](https://github.com/c2h5oh/hide/blob/master/inverse.go#L49) from `val.And` to `val.Rem`, the second run (using custom prime) works, but not the first one.

**Comment by c2h5oh** [comment]
There was a bug in prime inverse calculation (off by one early in) that is fixed now. 

See: https://github.com/c2h5oh/hide/blob/master/inverse.go#L67
