### ISSUE TITLE
Question about readme

### ISSUE THREAD

**Issue by qgustavor** [c2h5oh/hide#5]
> * Base64-encoded IDs (Youtube-like):
>    * they are just regular autoincrement IDs displayed in a different format that is trivial to reverse
 
YouTube IDs are [Base64 encoded using the URL variant](https://en.wikipedia.org/wiki/Base64#URL_applications). That's verificable because it ignores the higher bits when decoding. Example: [jNQXAC9IVRw](https://www.youtube.com/watch?v=jNQXAC9IVRw), [jNQXAC9IVRx](https://www.youtube.com/embed/jNQXAC9IVRx), [jNQXAC9IVRy](https://www.youtube.com/embed/jNQXAC9IVRy), [jNQXAC9IVRz](https://www.youtube.com/embed/jNQXAC9IVRz) returns the same video.

The issue is "that is trivial to reverse": can you source that? If would trivial to reverse then unlisted videos wouldn't work. My guess is that YouTube is taking the "autoincrement ID", encrypting it with [some 64-bit block cipher](http://en.citizendium.org/wiki/Block_cipher/Catalogs/Cipher_list#64-bit_blocks) then encoding using Base64.

**Comment by c2h5oh** [comment]
I'm calling it Youtube-like to describe how the obfuscated IDs look like. I don't know what Youtube does internally to the value (or how the value is generated) before base64 encode.

If base64 encode is all you do (and I've seen it that happen) it is trivially reversible - simply base64 decode.

**Comment by qgustavor** [comment]
So it's not trivial to reverse, unlike the readme says?

**Comment by c2h5oh** [comment]
Base64 encoded IDs are trivial to reverse if that's the only thing you're doing. I'm going to clarify that, because this ticket shows it's possible to assume based on the README that I claim this the only thing Youtube is doing.

**Comment by qgustavor** [comment]
I think that comparison with YouTube is not fair because Base64 is just the
encoding, it don't handles integer obfucation.

Of course, someone could take the result from your library (or similar) and
reinterpret in other base: decoding or encoding from some base it's just a
matter of presentation, what's important for the obfuscation is hiding the
data behind it.

So I could use store my integers in a 8 byte buffer, encrypt those with
Triple DES and encode with Base64. Of course, it's trivial to reverse the
Base64 step, what is not trivial is reversing the encryption step. Then if
you're going to compare your library with YouTube don't consider only the
final step, but all steps.

If YouTube could be using cryptography then their implementation is good:
it's not trivial to reverse (maybe impossible without the key), easy to
implement (on Node there's the crypto module), fast (on my computer OpenSSL
can process over one million 64 byte blocks per second using AES) and
versatile (they used Base64, but they could use Base32 or any other
encoding).

The issue - that your library don't have - IIRC - is that if you use crypto
you will get a large obfuscated value… unless you use less secure ciphers
that allows smaller block sizes. There's also homomorphic encryption, but
all NPM libraries for that I checked are insecure: one of those implements
a simple and weak substitution cipher.

The readme issue aside, IMHO thinking about this maybe can lead a good
improvements in your library.

2018/12/04 18:34 "Maciej Lisiewski" <notifications@github.com>:

Base64 encoded IDs are trivial to reverse if that's the only thing you're
doing. I'm going to clarify that, because this ticket shows it's possible
to assume based on the README that I claim this the only thing Youtube is
doing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/c2h5oh/hide/issues/5#issuecomment-444247870>, or mute
the thread
