### ISSUE TITLE
Does the confusion result in a conflict? 

### ISSUE THREAD

**Issue by andywu1998** [c2h5oh/hide#7]
hi:

Does it appear that a!=b, but the obfuscation result result_a=result_b

thanks!

**Comment by c2h5oh** [comment]
There is no pair of integers A,B where A != B and Obfuscate(A) == Obfuscate(B), Therefore  Obfuscate(A) == Obfuscate(B) only when A == B.

Or more plainly this is a reversible transformation and not a hash - collisions are not possible.

**Comment by andywu1998** [comment]
thank you!
